name: API
on:
  workflow_dispatch:
        
  schedule:
   - cron: 40 3 * * *

env:
  REPO_TOKEN: ${{ github.token }}
  TZ: Asia/Shanghai

jobs:
  build:
    name: API
    runs-on: ubuntu-22.04
    
    steps:
    - name: 准备结束
      uses: actions/checkout@v4
      
    - name: 部署环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y git subversion git-core wget curl grep jq
        sudo timedatectl set-timezone "$TZ"
        
    - name: 下载API
      run: |
        cd ${GITHUB_WORKSPACE}
        mkdir -p Github_Api
        cd Github_Api
        curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/ophub/kernel/releases/tags/kernel_stable -o stable.api
        if [[ $? -ne 0 ]]; then
          curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/ophub/kernel/releases/tags/kernel_stable > stable.api
        fi
        
        curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/ophub/kernel/releases/tags/kernel_flippy -o flippy.api
        if [[ $? -ne 0 ]]; then
          curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/ophub/kernel/releases/tags/kernel_flippy > flippy.api
        fi
        
        curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/ophub/kernel/releases/tags/kernel_rk3588 -o rk3588.api
        if [[ $? -ne 0 ]]; then
          curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/ophub/kernel/releases/tags/kernel_rk3588 > rk3588.api
        fi
        
        curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/ophub/kernel/releases/tags/kernel_dev -o dev.api
        if [[ $? -ne 0 ]]; then
          curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/ophub/kernel/releases/tags/kernel_dev > dev.api
        fi
        
        curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest -o AdGuardHome.api
        if [[ $? -ne 0 ]]; then
          curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest > AdGuardHome.api
        fi

        curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/tindy2013/subconverter/releases/latest -o tindy2013.api
        if [[ $? -ne 0 ]]; then
          curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/tindy2013/subconverter/releases/latest > tindy2013.api
        fi
        
    - name: 发布API
      uses: ncipollo/release-action@main
      with:
        name: API
        tag: API
        token: ${{ github.token }}
        artifacts: "Github_Api/*"
        allowUpdates: true
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}       
        retain_days: 0.1
        keep_minimum_runs: 0
