
name: Upload
on:
  repository_dispatch:
  workflow_dispatch:
  
  schedule:
   - cron: 40 3 * * 6

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: Ubuntu-22.04
    name: Upload
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y git subversion git-core wget curl grep
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
          
    - name: Organize data
      if: env.REPO_TOKEN
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/${{github.repository}}.git $GITHUB_WORKSPACE/repogx
        
        git clone --depth 1 https://github.com/openwrt/packages -b openwrt-21.02 $GITHUB_WORKSPACE/packr-version
        if [[ -d "$GITHUB_WORKSPACE/packr-version/lang/ruby" ]]; then
          rm -rf $GITHUB_WORKSPACE/repogx/Share/packr
          cp -Rf $GITHUB_WORKSPACE/packr-version/devel/packr $GITHUB_WORKSPACE/repogx/Share/packr
          rm -rf $GITHUB_WORKSPACE/repogx/Share/yaml
          cp -Rf $GITHUB_WORKSPACE/packr-version/libs/yaml $GITHUB_WORKSPACE/repogx/Share/yaml
          rm -rf $GITHUB_WORKSPACE/repogx/Share/ruby
          cp -Rf $GITHUB_WORKSPACE/packr-version/lang/ruby $GITHUB_WORKSPACE/repogx/Share/ruby
          rm -rf $GITHUB_WORKSPACE/repogx/Share/ttyd
          cp -Rf $GITHUB_WORKSPACE/packr-version/utils/ttyd $GITHUB_WORKSPACE/repogx/Share/ttyd
        fi

        git clone --depth 1 https://github.com/openwrt/luci -b openwrt-21.02 $GITHUB_WORKSPACE/ttyd-version
        if [[ -d "$GITHUB_WORKSPACE/ttyd-version/applications/luci-app-ttyd" ]]; then
          rm -rf $GITHUB_WORKSPACE/repogx/Share/luci-app-ttyd
          cp -Rf $GITHUB_WORKSPACE/ttyd-version/applications/luci-app-ttyd $GITHUB_WORKSPACE/repogx/Share/luci-app-ttyd
        fi
        
        git clone --depth 1 https://github.com/openwrt/packages -b master $GITHUB_WORKSPACE/golang-version
        if [[ -d "$GITHUB_WORKSPACE/golang-version/net/tailscale" ]]; then
          rm -rf $GITHUB_WORKSPACE/repogx/Share/tailscale
          cp -Rf $GITHUB_WORKSPACE/golang-version/net/tailscale $GITHUB_WORKSPACE/repogx/Share/tailscale
          rm -rf $GITHUB_WORKSPACE/repogx/Share/samba4
          cp -Rf $GITHUB_WORKSPACE/golang-version/net/samba4 $GITHUB_WORKSPACE/repogx/Share/samba4
          rm -rf $GITHUB_WORKSPACE/repogx/Share/perl-parse-yapp
          cp -Rf $GITHUB_WORKSPACE/golang-version/lang/perl-parse-yapp $GITHUB_WORKSPACE/repogx/Share/perl-parse-yapp
          rm -rf $GITHUB_WORKSPACE/repogx/Share/liburing
          cp -Rf $GITHUB_WORKSPACE/golang-version/libs/liburing $GITHUB_WORKSPACE/repogx/Share/liburing
          rm -rf $GITHUB_WORKSPACE/repogx/Share/btrfs-progs
          cp -Rf $GITHUB_WORKSPACE/golang-version/utils/btrfs-progs $GITHUB_WORKSPACE/repogx/Share/btrfs-progs
        fi

        git clone --depth 1 https://github.com/openwrt/luci -b master $GITHUB_WORKSPACE/samba-version
        if [[ -d "$GITHUB_WORKSPACE/samba-version/applications/luci-app-samba4" ]]; then
          rm -rf $GITHUB_WORKSPACE/repogx/Share/luci-app-samba4
          cp -Rf $GITHUB_WORKSPACE/samba-version/applications/luci-app-samba4 $GITHUB_WORKSPACE/repogx/Share/luci-app-samba4
        fi

        git clone --depth 1 https://github.com/coolsnowwolf/packages -b master $GITHUB_WORKSPACE/pcre-version
        if [[ -d "$GITHUB_WORKSPACE/pcre-version/libs/pcre2" ]]; then
          rm -rf $GITHUB_WORKSPACE/repogx/Share/glib2
          cp -Rf $GITHUB_WORKSPACE/pcre-version/libs/glib2 $GITHUB_WORKSPACE/repogx/Share/glib2
          rm -rf $GITHUB_WORKSPACE/repogx/Share/pcre2
          cp -Rf $GITHUB_WORKSPACE/pcre-version/libs/pcre2 $GITHUB_WORKSPACE/repogx/Share/pcre2
          rm -rf $GITHUB_WORKSPACE/repogx/Share/rust
          cp -Rf $GITHUB_WORKSPACE/pcre-version/lang/rust $GITHUB_WORKSPACE/repogx/Share/rust
        fi

        git clone --depth 1 https://github.com/openwrt/openwrt -b openwrt-23.05 $GITHUB_WORKSPACE/cdmake
        if [[ -d "$GITHUB_WORKSPACE/cdmake/tools/cmake" ]]; then
          rm -rf $GITHUB_WORKSPACE/repogx/Share/cmake
          cp -Rf $GITHUB_WORKSPACE/cdmake/tools/cmake $GITHUB_WORKSPACE/repogx/Share/cmake
        fi

        git clone --depth 1 https://github.com/openwrt/routing -b openwrt-21.02 $GITHUB_WORKSPACE/routing
        if [[ -d "$GITHUB_WORKSPACE/routing/bmx6" ]]; then
          rm -rf $GITHUB_WORKSPACE/repogx/Share/bmx6
          cp -Rf $GITHUB_WORKSPACE/routing/bmx6 $GITHUB_WORKSPACE/repogx/Share/bmx6
        fi
        
        git clone https://github.com/coolsnowwolf/lede $GITHUB_WORKSPACE/Lede
        git clone https://github.com/Lienol/openwrt $GITHUB_WORKSPACE/Lienol
        git clone https://github.com/immortalwrt/immortalwrt $GITHUB_WORKSPACE/Immortalwrt
        git clone https://github.com/openwrt/openwrt $GITHUB_WORKSPACE/Official
        git clone https://github.com/x-wrt/x-wrt $GITHUB_WORKSPACE/Xwrt
        echo "" >$GITHUB_WORKSPACE/123
        
        cd $GITHUB_WORKSPACE/Lede
        git branch -r |sed '/HEAD/d' |sed 's/openwrt-//g' |sed 's/master/23.05/g' |sed 's/$/-Lede\"/' |sed 's/origin\//=\"/g' >>$GITHUB_WORKSPACE/123
        cd $GITHUB_WORKSPACE/Lienol
        git branch -r |sed '/HEAD/d' |sed 's/openwrt-//g' |sed 's/$/-Lienol\"/' |sed 's/origin\//=\"/g' >>$GITHUB_WORKSPACE/123
        cd $GITHUB_WORKSPACE/Immortalwrt
        git branch -r |sed '/HEAD/d' |sed 's/openwrt-//g' |sed 's/$/-Immortalwrt\"/' |sed 's/origin\//=\"/g' >>$GITHUB_WORKSPACE/123
        echo '="mt798x-Immortalwrt"' >>$GITHUB_WORKSPACE/123
        cd $GITHUB_WORKSPACE/Official
        git branch -r |sed '/HEAD/d' |sed 's/openwrt-//g' |sed 's/$/-Official\"/' |sed 's/origin\//=\"/g' >>$GITHUB_WORKSPACE/123
        cd $GITHUB_WORKSPACE/Xwrt
        git branch -r |sed '/HEAD/d' |sed 's/openwrt-//g' |sed 's/$/-Xwrt\"/' |sed 's/origin\//=\"/g' >>$GITHUB_WORKSPACE/123
        cd $GITHUB_WORKSPACE
        cat $GITHUB_WORKSPACE/123 |sed '/^$/d' |awk '$0=NR$0' |sed 's/^/R/' |sed s/[[:space:]]//g >$GITHUB_WORKSPACE/repogx/autoupdate/replace
        
    - name: Upload
      continue-on-error: true
      if: env.REPO_TOKEN
      run: |
        cd $GITHUB_WORKSPACE
        chmod -R 775 repogx
        cd repogx
        git add .
        git commit -m "up"
        git push --quiet "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:main
